test: add log for errors

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,7 +22,9 @@ jobs:
         run: npm ci
 
       - name: Build Angular project
-        run: npm run build -- --configuration production --base-href "/enigma/"
+        run: npm run build -- --configuration production --base-href "/enigma/" || true
+          echo "=== BUILD FINISHED (maybe with error) ==="
+          ls -R dist || echo "dist folder not found"
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
